class TokenType:
	PROGRAM_TOK, ID_TOK, END_TOK, IF_TOK, LEFT_PAREN_TOK, RIGHT_PAREN_TOK, THEN_TOK, ELSE_TOK, DO_TOK, ASSIGNMENT_TOK, INT_TOK, WRITE_TOK, LE_TOK, LT_TOK, GE_TOK, GT_TOK, EQ_TOK, NE_TOK, ADD_TOK, SUB_TOK, MUL_TOK, DIV_TOK, COMMA_TOK, EOS_TOK = range(24)
