from enum import Enum


class TokenType(Enum):
	MODULE_TOK, BEGIN_TOK, END_TOK, IF_TOK, PRINT_TOK, REPEAT_TOK, UNTIL_TOK, WHILE_TOK, ID_TOK, DO_TOK, ELSE_TOK, THEN_TOK, ASSIGN_OP, LIT_INT, ADD_TOK, SUB_TOK, MUL_TOK, DIV_TOK, EQ_TOK, NE_TOK, LT_TOK, LE_TOK, GT_TOK, GE_TOK, EOS_TOK, SEMI_COLON_TOK, PERIOD_TOK, LEFT_PAREN_TOK, RIGHT_PAREN_TOK = range(29)
